### ISSUE TITLE
how to install? its working?

### ISSUE THREAD

**Issue by hakkemanu** [Glatrix/World-Of-Tanks-Aimbot#1]

**Comment by Glatrix** [comment]
This does not work anymore... Sorry!
go to [https://wotbaza.com/cheats-wot/291-aimbot-shaytan-from-zorrojan-for-world-of-tanks](url)

**Comment by hakkemanu** [comment]
this one is banned :)

**Comment by hakkemanu** [comment]
> This does not work anymore... Sorry!
> go to [https://wotbaza.com/cheats-wot/291-aimbot-shaytan-from-zorrojan-for-world-of-tanks](url)


thx working
